name: HavenQoL
version: '${version}'

main: me.david.havenQoL.HavenQoL
api-version: '26.1.2'
load: POSTWORLD

commands:
  sethome:
    description: Sets your home location.
    usage: /sethome
  home:
    description: Teleports player to home.
    usage: /home
  playerstats:
    description: Opens your player statistics menu.
    usage: /playerstats
  tpa:
    description: Sends a teleport request to another player.
    usage: /tpa <player>
  tpaccept:
    description: Accepts pending teleport request.
    usage: /tpaccept
  tpdeny:
    description: Denies pending teleport request.
    usage: /tpdeny